#!/usr/bin/env python3
"""Offline RAQM/HarfBuzz Bengali shaping; embedded coverage masks, not per-codepoint drawing.
Needs Pillow with libraqm. Source fonts and SIL OFL are included. No network at runtime.
"""
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont,features
import json,zlib
root=Path(__file__).resolve().parents[1]
assert features.check_feature('raqm'), 'Bengali must be shaped with RAQM'
strings=json.loads((root/'tools/ui_strings.json').read_text())
entries=[];data=[]
for size in [10,14,16,20,28]:
 for bengali,words in [(False,[chr(i) for i in range(32,127)]),(True,sorted(set(strings.values()) | {word for phrase in strings.values() for word in phrase.split()}))]:
  font=ImageFont.truetype(str(root/'assets/fonts'/('NotoSansBengali.ttf' if bengali else 'NotoSans.ttf')),size,layout_engine=ImageFont.Layout.RAQM)
  asc,desc=font.getmetrics()
  for word in words:
   if bengali and (size==28 or size==20 and len(word)>40 or size==16 and len(word)>90):continue
   width=max(1,int(font.getlength(word)+1));height=asc+desc+2
   im=Image.new('L',(width,height));ImageDraw.Draw(im).text((0,asc),word,font=font,fill=255,anchor='ls',language='bn' if bengali else 'en')
   values=list(im.getdata());rle=[];i=0
   while i<len(values):
    j=i+1
    while j<len(values) and values[j]==values[i] and j-i<255:j+=1
    rle.extend([j-i,values[i]]);i=j
   entries.append((word,size,width,height,len(data),len(rle)));data.extend(rle)
packed=list(zlib.compress(bytes(data),9))
out=root/'native/ui7_fonts.hpp'
with out.open('w') as f:
 f.write('// Generated by tools/build_ui_fonts.py. Noto fonts: SIL OFL.\n#pragma once\n#include <zlib.h>\nnamespace av {\nstruct UIFontEntry{const char* key;int size,w,h,offset,length;};\ninline const unsigned char uiFontPacked[]={\n')
 for i in range(0,len(packed),60):f.write(','.join(map(str,packed[i:i+60]))+',\n')
 f.write('};\ninline const std::vector<unsigned char> uiFontBytes=[](){std::vector<unsigned char> v('+str(len(data))+');uLongf n=v.size();if(uncompress(v.data(),&n,uiFontPacked,sizeof(uiFontPacked))!=Z_OK||n!=v.size())v.clear();return v;}();\ninline const UIFontEntry uiFontEntries[]={\n')
 for word,size,w,h,o,n in entries:f.write('{'+json.dumps(word,ensure_ascii=False)+f',{size},{w},{h},{o},{n}'+'},\n')
 f.write('};\ninline const std::pair<const char*,const char*> uiTranslations[]={\n')
 for en,bn in strings.items():f.write('{'+json.dumps(en)+','+json.dumps(bn,ensure_ascii=False)+'},\n')
 f.write('};\n}\n')
print(len(entries),'shaped/glyph masks,',len(data),'RLE bytes, header',out.stat().st_size)
