#!/usr/bin/env python3
"""Offline gallery from actual headless GL captures, never concept art."""
from pathlib import Path
from PIL import Image
import base64,io,json,sys
root=Path(__file__).resolve().parents[1]
captures=Path(sys.argv[1]);output=Path(sys.argv[2])
def uri(name):
 im=Image.open(captures/(name+'.ppm')).convert('RGB');b=io.BytesIO();im.save(b,format='WEBP',lossless=True,method=6)
 assert Image.open(io.BytesIO(b.getvalue())).convert('RGB').tobytes()==im.tobytes()
 return 'data:image/webp;base64,'+base64.b64encode(b.getvalue()).decode()
labels={'forest-walk':'সাধারণ বন','forest-road':'বনের পথ','camp-day':'শিবির · দিন','camp-night':'শিবির · রাত','desert':'মরুভূমি','snow':'তুষার','swamp':'জলাভূমি','volcanic':'আগ্নেয় অঞ্চল'}
scenes={k:{'label':v,'low':uri(k+'-low'),'medium':uri(k+'-medium')} for k,v in labels.items()}
html='''<!doctype html><html lang="bn"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Death World 0.9 — Low / Medium</title>
<style>*{box-sizing:border-box}body{margin:0;background:#101b1d;color:#e8e9dc;font-family:system-ui,sans-serif;line-height:1.7}main{max-width:1240px;margin:auto;padding:38px 24px 64px}header{border-bottom:1px solid #3a4b43;padding-bottom:25px}.eyebrow{letter-spacing:.2em;font-size:11px;color:#c0ac7c;text-transform:uppercase}h1{font-size:clamp(28px,4vw,48px);line-height:1.2;font-weight:600;margin:14px 0}h2{font-size:24px;margin:38px 0 12px}.muted{color:#acbfb3;font-size:14px}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.chip{border:1px solid #56644e;border-radius:24px;padding:5px 13px;color:#d7c99e;font-size:12px}nav{display:flex;gap:8px;flex-wrap:wrap;margin:25px 0 16px}button{font:inherit;color:#cbd6ca;background:#1b2d2c;border:1px solid #41524a;border-radius:8px;padding:8px 14px;cursor:pointer}button[aria-pressed=true]{background:#d2bd86;color:#162426;border-color:#d2bd86}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin:12px 0}.toolbar h2{margin:0;font-size:20px}.stage{position:relative;aspect-ratio:16/9;border:1px solid #4d5c4a;overflow:hidden;background:#080f11}.stage img{position:absolute;width:100%;height:100%;image-rendering:pixelated;object-fit:contain}.right{clip-path:inset(0 0 0 var(--split,50%))}.divider{position:absolute;left:var(--split,50%);top:0;bottom:0;width:2px;background:#f0d897;pointer-events:none}.tag{position:absolute;top:12px;background:#101b1ddd;padding:4px 11px;font-size:12px;border:1px solid #6c7655}.tag.low{left:12px}.tag.medium{right:12px}.slider{display:flex;gap:16px;align-items:center;margin:16px 0}.slider input{width:100%;accent-color:#d2bd86}.pair{display:none;grid-template-columns:1fr 1fr;gap:14px}.pair figure{margin:0}.pair img,.maps img{width:100%;image-rendering:pixelated;display:block;border:1px solid #4a5a4d}figcaption{padding:8px 0;color:#c4cab7;font-size:13px}.maps{display:grid;grid-template-columns:1fr 1fr;gap:22px}.maps figure{margin:0}.note{background:#1a2c2a;border-left:3px solid #b39d6a;padding:15px 18px;color:#c5d0bf;margin:20px 0}.footer{border-top:1px solid #3a4b43;margin-top:40px;padding-top:20px;color:#a4b8ae;font-size:13px}@media(max-width:700px){main{padding:24px 14px 40px}.pair,.maps{grid-template-columns:1fr}button{font-size:13px;padding:7px 10px}.tag{font-size:10px}.slider label{font-size:12px;white-space:nowrap}}</style>
<main><header><div class="eyebrow">OBSIDIAN GAMES · DEATH WORLD · 0.9 PREVIEW</div><h1>একই জগৎ।<br>দুটি graphics tier।</h1><p class="muted">বর্তমান চেহারা অক্ষত Low; নতুন চরিত্র, surface lighting ও স্পষ্ট HUD-সহ Medium। নিচের ছবিগুলো বাস্তব native renderer থেকে—mockup নয়।</p><div class="chips"><span class="chip">১৪/১৪ native ও shader test PASS</span><span class="chip">৭২টি Low frame হুবহু অক্ষত</span><span class="chip">ফোনের FPS পরীক্ষা হয়নি</span></div></header>
<nav id="scenes" aria-label="দৃশ্য নির্বাচন"></nav>
<div class="toolbar"><h2 id="sceneTitle"></h2><button id="layout">পাশাপাশি দেখুন</button></div>
<div class="stage" id="stage"><img id="low" alt="Low renderer"><img id="medium" class="right" alt="Medium renderer"><div class="divider"></div><span class="tag low">LOW · আগের চেহারা</span><span class="tag medium">MEDIUM · নতুন renderer</span></div>
<div class="slider" id="sliderBox"><label for="split">বিভাজক সরান</label><input id="split" type="range" min="0" max="100" value="50" aria-label="Low Medium বিভাজক"></div>
<div class="pair" id="pair"><figure><img id="pairLow" alt="Low"><figcaption>Low · preserved renderer</figcaption></figure><figure><img id="pairMedium" alt="Medium"><figcaption>Medium · normal-map GPU lighting</figcaption></figure></div>
<p class="muted">Seed 20261005 · নতুন generator 5 · একই অবস্থান ও সময় · তুলনায় camera zoom একই রাখা হয়েছে। UI-তে আলো/blur লাগানো হয়নি। সব ছবি lossless; internet প্রয়োজন নেই।</p>
<div class="note">এটি একই নতুন world-এর উপর দুটি renderer-এর তুলনা। Medium পুরোনো world-এও চলে, কিন্তু পুরোনো save-এর জমি/রাস্তা বদলায় না। তাই নতুন বন-layout দেখতে নতুন world তৈরি করতে হবে।</div>
<h2>বনের grid: শুধু texture নয়, generator-ও বদলেছে</h2>
<p class="muted">একই seed-এর ২৫৬×২৫৬ টাইলের diagnostic overview। এটি ইন-গেম explored-only মানচিত্র নয়। গাঢ় সবুজ: গাছ, নীল: জল, বাদামি: পথ/শিবির।</p>
<div class="maps"><figure><img src="OLDMAP" alt="পুরোনো generator 4-এর grid road"><figcaption>পুরোনো generator 4 · প্রতি ৩২ টাইলে road grid</figcaption></figure><figure><img src="NEWMAP" alt="নতুন generator 5-এর sparse curved paths"><figcaption>নতুন generator 5 · ছড়ানো গাছের গুচ্ছ, বাঁকানো sparse পথ</figcaption></figure></div>
<h2>যা এখনো চূড়ান্ত নয়</h2><div class="note">Medium এখন hybrid: CPU-তে sprite/normal buffer composition, GPU-তে প্রকৃত normal-map আলো ও post-process। সম্পূর্ণ GPU atlas batching/compression, সব props/wildlife-এর নতুন bespoke art ও পূর্ণ inventory-icon overhaul শেষ হয়নি। Android ফোনে sustained FPS, thermal ও battery ফল এখনো মাপা হয়নি।</div>
<div class="footer">Captured with the shipping C++ renderer and GLES shaders on host Mesa/llvmpipe. Not Android phone screenshots, not an FPS certification, not a claim of studio-art parity. Prototype asset templates are original procedural pixel art.</div></main>
<script>const data=SCENEDATA;const $=id=>document.getElementById(id);let scene='forest-walk',side=false;
function show(k){scene=k;const s=data[k];$('sceneTitle').textContent=s.label;$('low').src=$('pairLow').src=s.low;$('medium').src=$('pairMedium').src=s.medium;document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.key===k?'true':'false'));}
for(const [k,s] of Object.entries(data)){const b=document.createElement('button');b.textContent=s.label;b.dataset.key=k;b.onclick=()=>show(k);$('scenes').appendChild(b);}
$('split').oninput=e=>$('stage').style.setProperty('--split',e.target.value+'%');$('layout').onclick=()=>{side=!side;$('stage').style.display=side?'none':'block';$('sliderBox').style.display=side?'none':'flex';$('pair').style.display=side?'grid':'none';$('layout').textContent=side?'বিভাজক দিয়ে দেখুন':'পাশাপাশি দেখুন';};show(scene);</script></html>'''
html=html.replace('SCENEDATA',json.dumps(scenes,ensure_ascii=False)).replace('OLDMAP',uri('generation-4')).replace('NEWMAP',uri('generation-5'))
output.parent.mkdir(parents=True,exist_ok=True);output.write_text(html)
print('Created offline lossless gallery:',output,output.stat().st_size,'bytes')
